FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["EVCharging.PaymentService.csproj", "./"]
RUN dotnet restore "EVCharging.PaymentService.csproj"
COPY . .
RUN dotnet build "EVCharging.PaymentService.csproj" -c Release -o /app/build

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/build .
EXPOSE 8080
ENTRYPOINT ["dotnet", "EVCharging.PaymentService.dll"]